### ISSUE TITLE
Missing "music_menu.mp3"

### ISSUE THREAD

**Issue by Gadgetoid** [ThePythonator/Super-Square-Bros#1]
When building, the Python asset builder fails with:

```
RuntimeError: Input file(s) assets/music_menu.mp3 not found for output assets.cpp.
```

Needs `assets/music_menu.mp3` added to source control.

**Comment by Daft-Freak** [comment]
Most of the other `music_*.mp3`s too, since they're unused I just commented them out...

**Comment by ThePythonator** [comment]
I haven't updated the tools for a while, but I know I had music files listed in `assets.yml` which I hadn't got around to composing. It doesn't break with older versions (it used to skip missing files), so I'm guessing a recent-ish change causes the asset builder to stop when it encounters a missing file.
